@extends('layouts/fullLayoutMaster')

@section('content')

<section class="terms-condition-wrap faq-wrap pb-2">
	<div class="container">
		<div class="terms-condition-content">
			<h2>PRIVACY POLICY</h2>

			<div style="margin-top: 20px; text-align: justify;">
				<p>
                    <ol class="privacyPolicy">
                        <li>Introduction</li>
                            Binge provides a subscription-based service for multiscreen (TV and Mobile) that allows users to access Live TV Channels and VOD contents that includes (but not limited to) Drama, Movies, Music Videos TV shows and so on streamed over internet. Binge is the brand for streaming Service that is owned and operated by RedDot Digital Limited (hereinafter referred to as "Binge", "Site", "Website", "us", "we" or "our"). RedDot Digital Limited is committed to safeguarding the privacy of Binge's (large screen and small screen App) visitors. This policy sets out how personal information will be treated. This Privacy Policy applies to all Visitors and Users (collectively referred to as "Users"). In addition, this Privacy Policy applies to all products and services provided by this site.<br /><br />
                            <strong>Information We Collect</strong><br /><br />
                        <li>User provided information</li>
                            Binge’s primary purpose in collecting and storing personal information of subscriber provided by subscriber while registration such as Mobile number, Gender, Name, Birthdate, User’s Photo(Profile Picture), user preference, user Rating on VOD, billing pack preference  to provide subscriber with a safe, smooth, efficient, and customized experience. Binge never stores, receives or has access to any bank account details, debit card, credit card information from user. Binge also doesn’t access or stores any data from the user’s phone book or contact list. This information is collected in a number of ways, including when entering it while using the platform: Information is collected when subscribers use the services provided by Binge, interact with Customer Service, or participate in surveys or marketing promotions via different platform.<br /><br />
                        <li>Information Collected Automatically</li>
                            Binge collects information about subscribers and their usage behavior of service, their interactions with Binge’s advertising, as well as information regarding subscriber’s computer, handheld device or other device used to access Binge’s service (such as gaming systems, smart TVs, mobile devices, and set top boxes). This information includes: subscriber’s activity on Binge service, such as title selections, watch history and search queries; details of subscriber’s interactions with Customer Service, such as the date, time and reason for contacting Binge, transcripts of any chat conversations, and if subscribers call Binge, their phone number and call recordings; device IDs or other unique identifiers; device and software characteristics (such as type and configuration), connection information, statistics on page views, referral URLs, IP address (which may inform Binge user's general location), browser and standard web server log information. Information collected via the use of cookies, web beacons and other technologies, including ad data (such as information on the availability and delivery of ads, the site URL, as well as the date and time).<br /><br />
                        <li>Information Received from Other Sources</li>
                            We also may obtain information from other sources and combine that with information we collect through the Platform. For example, if you create an account using your credentials from a third-party websites (such as but not limited to Google, Facebook and others), we will have access to certain information from that site, such as your name, profile and account information, such as lists of your friends, "likes", comments you have shared, groups and location, in accordance with the authorization procedures determined by such third-party social media site. Services like Facebook Connect give you the option to post information about your activities on our Platform to your profile page to share with others within your network. In addition, we may receive information about you if other users of a third party application or website give us access to their profiles and you are one of their "connections" or information about you is otherwise accessible through your "connections'" web page, profile page, or similar page on a social networking or other third party website or interactive service.<br /><br />
                            We may also receive information about users from our partners and service providers, (including, for example, business partners, analytics vendors and search information providers) which we use to personalize your experience on the Platform.<br /><br />
                        <li>How we use the information</li>
                            Binge's primary purpose in collecting personal information is to provide subscribers with a safe, smooth, efficient, and customized experience. Binge may use subscriber’s personal information to:<br /><br />
                            <ul>
                                <li>Administer Binge service (Multiscreen) Perform market research, Platform analytics and operations;</li>
                                <li>Deliver ordered products, provide the services and customer support you request</li>
                                <li>Resolve disputes, securing payments against purchase, and troubleshoot problems</li>
                                <li>Customize your experience; detect and protect us against error</li>
                                <li>Prevent potentially prohibited or illegal activities, and enforce our Terms of Use</li>
                                <li>Customize, measure and improve our services, content and advertising</li>
                                <li>Inform subscribers about online and offline offers, products, services, and updates · Tell subscribers about their services and those of potential customers, targeted marketing, service updates, and promotional offers based on subscriber’s communication preferences</li>
                                <li>Tell you about our services and those of our corporate family, targeted marketing, service updates, and promotional offers based on your communication preferences</li>
                                <li>Compare subscriber’s submitted/tracked information for accuracy, and verify it with third parties</li>
                                <li>Examine subscriber’s personal information to identify users using multiple User IDs or aliases and delete/bar the unauthenticated User IDs</li>
                                <li>Send e-mail notifications to subscribers which they have specifically requested</li>
                                <li>Subscriber’s feedback, ratings and associated comments may be displayed for the enhancement of Binge multiscreen service and in-depth understanding for other visitors.</li>
                            </ul>
                        <li>Disclosure of the Information</li>
                            Binge doesn’t sell or rent subscriber’s personal information to third parties for their marketing purposes. This does not include website hosting partners and other parties who assist Binge in operating Binge service (multiscreen), conducting its business, or servicing subscribers, so long as those parties agree to keep this information confidential. Binge may combine subscriber’s information with information it collects from other companies and use it to improve and personalize its services, content and advertising.<br /><br />
                            Binge may disclose personal information to respond to legal requirements, enforce its policies, respond to claims that a listing or other content violates the rights of others, or protect anyone's rights, property, or safety. Such information will be disclosed in accordance with applicable laws and regulations of the country. Binge may also share subscriber’s personal information with:<br /><br />
                            <ul>
                                <li>Relevant Members/Partners/Vendors/Payment Gateway/Bank/Financial Institutes/Suppliers of Binge to provide joint content and services (like registration, transactions, fund collection and customer support), to help detect and prevent potentially illegal acts and violations of its policies, and to guide decisions about their products, services and communications. Members of its corporate family will use this information to send marketing communications to subscribers only if they have requested their services.</li>
                                <li>Service providers under contract, who help with its business operations (such as fraud investigations, bill collection, affiliate and rewards programs and co-branded credit cards)</li>
                                <li>Other third parties whom subscribers explicitly ask Binge to send their information (or about whom subscribers are otherwise explicitly notified and consent to when using a specific service)</li>
                                <li>Law enforcement or other governmental officials, in response to a verified request relating to a criminal investigation or alleged illegal activity. In such events, Binge will disclose information relevant to the investigation.</li>
                                <li>For any confidentiality agreement between Binge and any other organization, Binge in its sole discretion believe necessary or appropriate in connection with an investigation of fraud, intellectual property infringement, piracy, or other unlawful activity. In such events, Binge will disclose necessary information.</li>
                                <li>Other business entities, should Binge plan to merge with or be acquired by that business entity. (Should such a combination occur, Binge shall require that the new combined entity follow this privacy policy with respect to subscriber’s personal information. If subscriber’s personal information will be used contrary to this policy, they will receive prior notice)</li>
                                <li>Without limiting the above, in an effort to respect subscriber’s privacy and its ability to keep the community free from bad actors, Binge will not otherwise disclose subscriber’s personal information to law enforcement, other government officials, or other third parties without a court order or substantially similar legal procedure, except when it believes in good faith that the disclosure of information is necessary to prevent imminent physical harm or financial loss or to report suspected illegal activity.</li>
                            </ul>
                        <li>Security</li>
                            Binge uses commercially reasonable security practices and procedures industry practices and procedures designed to help keep user's Personal Information or Sensitive Personal Data or Information safe. Secure Sockets Layer (SSL) encrypts all information user submit before it is sent to the Binge. Furthermore, all of the User data to be collected is protected against unauthorized access. To prevent unauthorized access, maintain data accuracy, and ensure correct use of information, we employ commercially reasonable and practicable security practices and procedures and security methods and technologies. it will also be ensured that any agent or third party that Binge employ complies with the same security standards as Binge do for the protection of user's Personal Information or Sensitive Personal Data or Information.<br /><br />
                            Unfortunately, the transmission of information over the Internet is not completely secure. Although we strive to protect your personal data, we cannot guarantee the security of your data while it is being transmitted to our site; any transmission is at your own risk. Once we have received your information, we have commercially reasonable procedures and security practices in place to reasonably endeavor to prevent unauthorized access."<br /><br />
                        <li>Cookies</li>
                            Our Website uses cookies; by using our Website and/or agreeing to the Terms, you consent to our use of cookies in accordance with the terms of our Privacy Policy. Binge uses "cookies" (small files placed on subscriber’s hard drive) on its certain pages to help analyze its web page flow; customize its services, content and advertising; measure promotional effectiveness, and promote trust and safety. A few important things that subscribers should know about cookies are:<br /><br />
                            <ul>
                                <li>Binge offers certain features that are available only through the use of cookies</li>
                                <li>Binge uses cookies to help identify subscribers and maintain their signed-in status</li>
                                <li>Most cookies are "session cookies," meaning that they are automatically deleted from subscriber’s hard drive at the end of a session</li>
                                <li>Subscribers are always free to decline Binge’s cookies if their browser permits, although doing so may interfere with subscriber’s use of some of sites or services of Binge</li>
                                <li>Subscribers may encounter cookies from third parties on certain pages of the sites that Binge does not control. (For example, if subscribers view a web page created by another user, there may be a cookie placed by that web page.) Binge uses Google Analytics &amp; facebook analytics to analyze the use of Binge service’s platform (Website, App). Google Analytics &amp; facebook analytics generates statistical and other information about website use by means of cookies, which are stored on users' computers. The information generated relating to Binge’s website is used to create reports about the use of the website. Google &amp; facebook will store this information. Google's privacy policy is available at: http://www.google.com/privacypolicy.html. Facebook’s privacy policy is available at: https://www.facebook.com/policy.php</li>
                            </ul>
                        <li>General/ Amendment/ contact us</li>
                            From time to time we may update this Privacy Policy. You’re continued Use of the Platform and the Services constitutes your acceptance of the current Privacy Policy and Terms of Use so we encourage you to visit this page periodically to review any changes. Subscriber can also provide feedback through the Binge app. Subscriber is welcomed to call Binge hotline number 01841024643 for any queries/suggestions. For any query about this Privacy Policy, the practices of Binge or user's dealings with the Platform, customer can contact us at info@binge.buzz or at the Head Office: Plot 1, Block 6, Bangabandhu Hi-Tech City. Kaliakair, Gazipur, Bangladesh.<br />
                    </ol>
				</p>
			</div>

		</div>
	</div>
</section>

@endsection

